### ISSUE TITLE
duplicate z wave devices

### ISSUE THREAD

**Issue by catsartcox** [timcharper/homebridge-vivint#14]
The three z-wave style devices I have on my Vivint system - The Front door lock, the garage door, and the plug switch are all showing twice in the home app. Only one of each of those actually functions though, the other is unresponsive If I try to toggle it.

**Comment by balansse** [comment]
Did you try deleting the Homebridge cache in .homebridge/ directory?

**Comment by catsartcox** [comment]
> Did you try deleting the Homebridge cache in .homebridge/ directory?

That did the trick, thank you.
