### ISSUE TITLE
Vivint Garage Door Being Detected as Contact Sensor

### ISSUE THREAD

**Issue by brianpham** [timcharper/homebridge-vivint#17]
Are there any special configuration I need to do to get the garage door functioning with homekit? It is being detected as a contact sensor from the home app.

**Comment by balansse** [comment]
Most probably what you are referring to as the garage door is actually a garage door tilt sensor. You can try my [fork](https://github.com/balansse/homebridge-vivint) of the Vivint plugin  - in one of the recent updates I added support for a bunch of new devices, maybe it will fix your setup.

**Comment by brianpham** [comment]
Thanks @balansse! Will give it a shot.

**Comment by brianpham** [comment]
Yay it's working @balansse 🙂 Going to close this issue and use your fork
