### ISSUE TITLE
Motion & Contact Sensors Not Working

### ISSUE THREAD

**Issue by zellunit** [timcharper/homebridge-vivint#34]
I have 4 motion sensors, 4 door contact sensors, and 6 window sensors all professionally installed by Vivint and they work A+ well detecting motion, opens, closes, etc through the core Vivint App and Panel. But when I bring them into Apple Home through HomeBridge via Hoobs, they all do successfully show up as accessories, but do not function at all. No motion events. No open events. Everything just shows as "closed". And all the batteries indicate "low" even when they are not.

Do I need to do something special to whitelist these devices?

**Comment by balansse** [comment]
What version of the package are you using? 

Also, please look at the log file and paste here it's contents, might be helpful.

**Comment by zellunit** [comment]
oh s*** never mind. when searching for the latest package hoobs switched out homebridge-vivint for homebridge-vivint-latest 0.0.7 published 6/12/2020 that was broken. switched back and now it works beautifully. thank you. and sorry for the false alarm.

i will publish what i was seeing below and close the issue out.

***

homebridge-vivint-latest 0.0.7 published 6/12/2020

7/7/2020, 8:48:24 PM Loaded plugin "homebridge-vivint-latest".

7/7/2020, 8:48:27 PM [Vivint] Do not know how to handle device! ID: 5 Data.t: energy_service data.ec: undefined Data.n: undefined
7/7/2020, 8:48:27 PM [Vivint] Do not know how to handle device! ID: 12 Data.t: network_hosts_service data.ec: undefined Data.n: undefined
7/7/2020, 8:48:27 PM [Vivint] Do not know how to handle device! ID: 13 Data.t: panel_diagnostics_service data.ec: undefined Data.n: undefined
7/7/2020, 8:48:27 PM [Vivint] Do not know how to handle device! ID: 23 Data.t: wireless_sensor data.ec: 873 Data.n: Front Door
7/7/2020, 8:48:27 PM [Vivint] Do not know how to handle device! ID: 25 Data.t: wireless_sensor data.ec: 609 Data.n: First Floor Motion Detector
7/7/2020, 8:48:27 PM [Vivint] Do not know how to handle device! ID: 26 Data.t: wireless_sensor data.ec: 609 Data.n: Second Flood Motion Detector
7/7/2020, 8:48:27 PM [Vivint] Do not know how to handle device! ID: 27 Data.t: wireless_sensor data.ec: 609 Data.n: Third Floor Motion Detector
7/7/2020, 8:48:27 PM [Vivint] Do not know how to handle device! ID: 37 Data.t: wireless_sensor data.ec: 2081 Data.n: RPTR1
7/7/2020, 8:48:27 PM [Vivint] Do not know how to handle device! ID: 38 Data.t: keypad_device data.ec: 867 Data.n: Keypad One
7/7/2020, 8:48:27 PM [Vivint] Do not know how to handle device! ID: 39 Data.t: wireless_sensor data.ec: 1269 Data.n: Fire Alert
7/7/2020, 8:48:27 PM [Vivint] Do not know how to handle device! ID: 42 Data.t: iot_service data.ec: undefined Data.n: undefined
7/7/2020, 8:48:27 PM [Vivint] Do not know how to handle device! ID: 44 Data.t: scheduler_service data.ec: undefined Data.n: undefined
7/7/2020, 8:48:27 PM [Vivint] Do not know how to handle device! ID: 47 Data.t: yofi_device data.ec: undefined Data.n: AirBridge-47
7/7/2020, 8:48:27 PM [Vivint] Adding 0 new accessories
7/7/2020, 8:48:27 PM [Vivint] Handling incoming device snapshot for timestamp 2020-07-08T03:36:22.920000

**Comment by zellunit** [comment]
hey @balansse thank you for the help. also, sorry, but i am reopening this issue i declared victory too soon. switching from vivint-latest back to this package properly fixed 70% of the devices where i get open/close/motion events. great. but a few issues still remain:

1. a few devices still don't show up. they happen to be ones that the last package was logging errors about (see below). is there a way to add these device types?
2. ever since switching back to homebridge-vivint from homebridge-vivint-latest, logging has stopped in my console. i see no errors other than " Loaded plugin "homebridge-vivint" ". but the devices referred to in (1) are still definitely not showing up.
3. all battery levels in every device, even the "functioning" ones, say 1%. is that just not supported generally?

despite 15 others working now, here's the 7 devices still not showing up:

7/7/2020, 8:48:27 PM [Vivint] Do not know how to handle device! ID: 23 Data.t: wireless_sensor data.ec: 873 Data.n: Front Door
7/7/2020, 8:48:27 PM [Vivint] Do not know how to handle device! ID: 25 Data.t: wireless_sensor data.ec: 609 Data.n: First Floor Motion Detector
7/7/2020, 8:48:27 PM [Vivint] Do not know how to handle device! ID: 26 Data.t: wireless_sensor data.ec: 609 Data.n: Second Flood Motion Detector
7/7/2020, 8:48:27 PM [Vivint] Do not know how to handle device! ID: 27 Data.t: wireless_sensor data.ec: 609 Data.n: Third Floor Motion Detector
7/7/2020, 8:48:27 PM [Vivint] Do not know how to handle device! ID: 37 Data.t: wireless_sensor data.ec: 2081 Data.n: RPTR1
7/7/2020, 8:48:27 PM [Vivint] Do not know how to handle device! ID: 38 Data.t: keypad_device data.ec: 867 Data.n: Keypad One
7/7/2020, 8:48:27 PM [Vivint] Do not know how to handle device! ID: 39 Data.t: wireless_sensor data.ec: 1269 Data.n: Fire Alert

any ideas?

**Comment by balansse** [comment]
It's hard to determine what happened as multiple versions were installed, could you reset the accessories cache and try again?

I believe the author is not supporting this repo anymore - I just published my latest changes under the "@balansse/homebridge-vivint" package. Please try that and let me know.

**Comment by zellunit** [comment]
@balansse, running yours now. v0.0.8 that you pushed a day ago. unfortunately, still see battery levels all at 1% and those 7 devices still don't show up. is there something i need to do specifically to force the cache reset? or should it now happen automatically per the latest notes?

**Comment by balansse** [comment]
@zellunit I just published a new version of the package where I included your sensors so they should appear in HomeKit now. It should also fix the battery reporting issues for the devices that do not report their battery level to Vivint.

The following ones
`7/7/2020, 8:48:27 PM [Vivint] Do not know how to handle device! ID: 37 Data.t: wireless_sensor data.ec: 2081 Data.n: RPTR1
7/7/2020, 8:48:27 PM [Vivint] Do not know how to handle device! ID: 38 Data.t: keypad_device data.ec: 867 Data.n: Keypad One`
are not relevant to HomeKit so you can just ignore them.

**Comment by zellunit** [comment]
@balansse thank you so much. i updated and restarted my server. still all batteries at 1% and no new devices. do i have to do something specific to roll that cache? i'm on hoobs and don't exactly know how. i can probably uninstall and reinstall the plugin entirely but i'll have to reset up all those previously working devices. please let me know. thank you again this will be a HUGE help.

**Comment by balansse** [comment]
It might happen because of the remnants of the old config, but 1% should definitely disappear as I removed all traces in the code that were setting battery levels to 1%. 

To clean the cache you'll need to delete the accessories/cachedAccessories directory from homebridge directory - the location of those folders depend on your homebridge setup.

**Comment by zellunit** [comment]
@balansse  i've deleted the accessories/cachedAccessories file and restarted the hoobs server. nothing changes and it recreates a clean cachedAccessories file again but it's empty only with [] inside. however nothing changes about the devices and same 1% bettery levels remain. do i also have to kill what's in the "persist" directory below? sorry about this just can't get this thing to roll...

hoobs@hoobs:~/.hoobs/etc $ cd accessories/
hoobs@hoobs:~/.hoobs/etc/accessories $ ls
cachedAccessories
hoobs@hoobs:~/.hoobs/etc/accessories $ rm cachedAccessories 
hoobs@hoobs:~/.hoobs/etc/accessories $ ls
hoobs@hoobs:~/.hoobs/etc/accessories $ cd ..
hoobs@hoobs:~/.hoobs/etc $ cd persist/
hoobs@hoobs:~/.hoobs/etc/persist $ ls
AccessoryInfo.10A0FEE1CF62.json  IdentifierCache.10A0FEE1CF62.json
AccessoryInfo.26E76A8473B3.json  IdentifierCache.26E76A8473B3.json
AccessoryInfo.5769C17A1D2A.json  IdentifierCache.5769C17A1D2A.json
AccessoryInfo.7B17BB590E7F.json  IdentifierCache.7B17BB590E7F.json
AccessoryInfo.7D60525C39D2.json  IdentifierCache.7D60525C39D2.json
AccessoryInfo.9F443E140B06.json  IdentifierCache.9F443E140B06.json
AccessoryInfo.B984992D082C.json  IdentifierCache.B984992D082C.json
AccessoryInfo.D3ECFE3DDD8E.json  IdentifierCache.D3ECFE3DDD8E.json
AccessoryInfo.F7D74F855D00.json  IdentifierCache.F7D74F855D00.json

**Comment by zellunit** [comment]
nvm, got it. hoobs was stuck in a loop and not fully rebooting. when i pulled the plug it came back and registered all the new devices. perfecto. closing this.
